# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intime <- function(x, y, z) {
    .Call('_rsMove_intime', PACKAGE = 'rsMove', x, y, z)
}

