# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
intime <- function(x, ij, oj, z) {
    .Call('_rsMove_intime', PACKAGE = 'rsMove', x, ij, oj, z)
}

