# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title storeLandsat
#'
#' @description Time-adjusted, linear interpolation.
#' @param x matrix with data to interpolate.
#' @param ij Numeric vector with julian days of input data.
#' @param oj Numeric vector with julian days of the output data.
#' @param z Two-element, numeric vector with temporal buffer.
#' @return A matrix.
#' @details {For each row in x, the function finds the two
#' nearest, non NA values to the target dates in ij retrieved
#' before and after this day. Then, the function linearly
#' interpolates the missing value linearly.}
#' @export
intime <- function(x, ij, oj, z) {
    .Call('_rsMove_intime', PACKAGE = 'rsMove', x, ij, oj, z)
}

